services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: third_space
      POSTGRES_USER: third_space
      POSTGRES_PASSWORD: third_space
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
